cabal-version:      3.0
name:               annuaire
version:            0.1.0.0

common deps
    ghc-options:      -Wall -O2
    build-depends:    base, containers, text
    default-language: GHC2024

library
    import:             deps
    hs-source-dirs:     src
    exposed-modules:    Model
                        Json
                        Yaml

executable annuaire
    import:             deps
    hs-source-dirs:     app
    build-depends:      annuaire
    main-is:            main.hs

