cabal-version:      3.0
name:               histogram
version:            0.1.0.0

common deps
    ghc-options:      -Wall -O2
    build-depends:    base, vector
    default-language: GHC2024

library
    import:           deps
    hs-source-dirs:   src
    exposed-modules:  Histogram

executable histogram
    import:           deps
    hs-source-dirs:   app
    main-is:          main.hs
    build-depends:    histogram

executable gendata
    import:           deps
    hs-source-dirs:   app
    main-is:          gendata.hs
    build-depends:    mwc-random

test-suite test
    import:           deps
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    build-depends:    hspec, histogram
    main-is:          Spec.hs
    other-modules:    HistogramSpec

