cabal-version:      3.0
name:               footix2000
version:            0.1.0.0

common deps
    ghc-options:      -Wall -O2
    default-language: GHC2024
    build-depends:    base
                    , effectful
                    , effectful-th
                    , log-effectful
                    , log-base
                    , lucid2
                    , scotty
                    , selda
                    , selda-sqlite
                    , text
                    , transformers
                    , wai-extra
                    , unliftio
                    , unliftio-core

library
    import:           deps
    hs-source-dirs:   src
    exposed-modules:  Applications.Html
                      Applications.Init
                      Applications.Params
                      Applications.Server
                      Domain.Country
                      Domain.Tournament
                      Effects.Db
                      Effects.Api
                      Interpreters.DbSelda
                      Interpreters.ApiDb

executable footix2000-init
    import:           deps
    hs-source-dirs:   app
    main-is:          footix2000-init.hs
    build-depends:    footix2000

executable footix2000-server
    import:           deps
    hs-source-dirs:   app
    main-is:          footix2000-server.hs
    build-depends:    footix2000

